return {
  {
    "AstroNvim/astroui",
    ---@type AstroUIOpts
    opts = {
      -- Icons can be configured throughout the interface
      icons = {
        -- configure the loading of the lsp in the status line
        LSPLoading1 = "⠋",
        LSPLoading2 = "⠙",
        LSPLoading3 = "⠹",
        LSPLoading4 = "⠸",
        LSPLoading5 = "⠼",
        LSPLoading6 = "⠴",
        LSPLoading7 = "⠦",
        LSPLoading8 = "⠧",
        LSPLoading9 = "⠇",
        LSPLoading10 = "⠏",

        DapBreakpoint = "",
        DapBreakpointCondition = "",
        DapBreakpointRejected = "",
        DapLogPoint = "",
        DapStopped = "",

        DefaultFile = "",
        Diagnostic = "",
        DiagnosticError = "",
        DiagnosticHint = "󱠁",
        DiagnosticInfo = "",
        DiagnosticWarn = "",
        WordFile = "󱀽",
        FileNew = "",
        Search = "",
        Projects = "",

        ActiveLSP = "",
        ActiveTS = " ",
        BufferClose = "",

        Ellipsis = "",
        FileModified = "",
        FileReadOnly = "",
        FoldClosed = "",
        FoldOpened = "",
        FolderClosed = "",
        FolderEmpty = "",
        FolderOpen = "",
        Git = "",
        GitAdd = "",
        GitBranch = "",
        GitChange = "",
        GitConflict = "",
        GitDelete = "",
        GitIgnored = "",
        GitRenamed = "",
        GitStaged = "",
        GitUnstaged = "",
        GitUntracked = "",
        LSPLoaded = "",
        MacroRecording = "",
        Paste = "",
        Selected = "",
        TabClose = "",
      },
    },
  },
  {
    "nvim-mini/mini.icons",
    optional = true,
    opts = {
      filetype = {
        -- cpp = { glyph = "󰙲", hl = "MiniIconsAzure" },
        -- cpp = { glyph = "", hl = "MiniIconsAzure" },
        -- yaml = { glyph = "", hl = "MiniIconsPurple" },
        -- sh = { glyph = "", hl = "MiniIconsGreen" },
        -- zsh = { glyph = "", hl = "MiniIconsGreen" },
        -- bash = { glyph = "", hl = "MiniIconsGreen" },
        -- fish = { glyph = "", hl = "MiniIconsGreen" },
      },
      extension = {
        -- h = { glyph = "󰫵", hl = "MiniIconsPurple" },
        h = { glyph = "", hl = "MiniIconsPurple" },
      },
      lsp = {
        array = { glyph = "" },
        boolean = { glyph = "" },
        key = { glyph = "" },
        namespace = { glyph = "" },
        null = { glyph = "" },
        number = { glyph = "" },
        -- object = { glyph = "" },
        object = { glyph = "" },
        package = { glyph = "" },
        string = { glyph = "" },
        class = { glyph = "" },
        color = { glyph = "" },
        constant = { glyph = "" },
        constructor = { glyph = "" },
        enum = { glyph = "" },
        enummember = { glyph = "" },
        event = { glyph = "" },
        field = { glyph = "" },
        file = { glyph = "" },
        folder = { glyph = "" },
        ["function"] = { glyph = "" },
        interface = { glyph = "" },
        keyword = { glyph = "" },
        method = { glyph = "" },
        module = { glyph = "" },
        operator = { glyph = "" },
        property = { glyph = "" },
        reference = { glyph = "" },
        snippet = { glyph = "" },
        struct = { glyph = "" },
        text = { glyph = "" },
        typeparameter = { glyph = "" },
        unit = { glyph = "" },
        value = { glyph = "" },
        variable = { glyph = "" },
      },
    },
  },
}
